CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE SCHEMA IF NOT EXISTS "user";

CREATE TABLE "user".roles (
	"id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	"name" VARCHAR(255) NOT NULL
	-- "permissions" VARCHAR(64)[]
);

CREATE TABLE "user".users (
	"id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	"username" VARCHAR(255) NOT NULL UNIQUE,
	"display_name" VARCHAR(255),
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"password" VARCHAR(255) NOT NULL,
	"verified" BOOLEAN NOT NULL DEFAULT false,
	"role_id" UUID NOT NULL REFERENCES "user".roles (id) ON DELETE RESTRICT,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"karma" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE "user".sessions (
	"id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	"user_id" UUID NOT NULL REFERENCES "user".users (id) ON DELETE CASCADE
);

CREATE SCHEMA IF NOT EXISTS forum;

CREATE TABLE forum.topics (
	"id"  INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"name" VARCHAR(255) NOT NULL
);

CREATE TABLE forum.threads (
	"id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"title" VARCHAR(255) NOT NULL,
	"user_id" UUID NOT NULL,
	"topic_id" INTEGER NOT NULL REFERENCES forum.topics (id) ON DELETE CASCADE,
	"tags" VARCHAR(255)[],
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"upvotes" INTEGER NOT NULL DEFAULT 0,
	"downvotes" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE forum.messages (
	"id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"thread_id" INTEGER NOT NULL REFERENCES forum.threads (id) ON DELETE CASCADE,
	"user_id" UUID NOT NULL,
	"title" VARCHAR(255) NOT NULL,
	"body" VARCHAR NOT NULL,
	"tags" VARCHAR(255)[],
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"upvotes" INTEGER NOT NULL DEFAULT 0,
	"downvotes" INTEGER NOT NULL DEFAULT 0
);

CREATE SCHEMA IF NOT EXISTS demo;

CREATE TABLE demo.demos (
	"id"  INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"title" TEXT NOT NULL,
	"description" TEXT,
	"tags" TEXT[],
	"link" VARCHAR(255) NOT NULL,
	"user_id" UUID NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"upvotes" INTEGER NOT NULL DEFAULT 0,
	"downvotes" INTEGER NOT NULL DEFAULT 0,
	"thread_id" INTEGER NOT NULL REFERENCES forum.threads (id) ON DELETE CASCADE
);

CREATE SCHEMA IF NOT EXISTS asset;

CREATE TABLE asset.assets (
	"id" INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"name" TEXT NOT NULL,
	"description" TEXT,
	"link" VARCHAR(255) NOT NULL,
	"tags" TEXT[],
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

---- create above / drop below ----

DROP SCHEMA IF EXISTS "user" CASCADE;
DROP SCHEMA IF EXISTS "demo" CASCADE;
DROP SCHEMA IF EXISTS "forum" CASCADE;
DROP SCHEMA IF EXISTS "asset" CASCADE;
DROP EXTENSION IF EXISTS "uuid-ossp";
