ALTER TABLE asset.assets ADD COLUMN views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE demo.demos ADD COLUMN views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE forum.threads ADD COLUMN views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE forum.messages ADD COLUMN views INTEGER NOT NULL DEFAULT 0;

ALTER TABLE demo.demos ALTER COLUMN views SET DEFAULT 1;
ALTER TABLE forum.threads ALTER COLUMN views SET DEFAULT 1;
ALTER TABLE forum.messages ALTER COLUMN views SET DEFAULT 1;

ALTER TABLE asset.assets ADD COLUMN upvotes INTEGER NOT NULL DEFAULT 1;
ALTER TABLE asset.assets ADD COLUMN downvotes INTEGER NOT NULL DEFAULT 1;

ALTER TABLE asset.assets ADD COLUMN rating DECIMAL GENERATED ALWAYS AS (upvotes::DECIMAL / downvotes) STORED;
ALTER TABLE demo.demos ADD COLUMN rating DECIMAL GENERATED ALWAYS AS (upvotes::DECIMAL / downvotes) STORED;
ALTER TABLE forum.threads ADD COLUMN rating DECIMAL GENERATED ALWAYS AS (upvotes::DECIMAL / downvotes) STORED;
ALTER TABLE forum.messages ADD COLUMN rating DECIMAL GENERATED ALWAYS AS (upvotes::DECIMAL / downvotes) STORED;

---- create above / drop below ----

ALTER TABLE demo.demos DROP COLUMN IF EXISTS views;
ALTER TABLE asset.assets DROP COLUMN IF EXISTS views;
ALTER TABLE forum.threads DROP COLUMN IF EXISTS views;
ALTER TABLE forum.messages DROP COLUMN IF EXISTS views;

ALTER TABLE demo.demos ALTER COLUMN views SET DEFAULT 0;
ALTER TABLE forum.threads ALTER COLUMN views SET DEFAULT 0;
ALTER TABLE forum.messages ALTER COLUMN views SET DEFAULT 0;

ALTER TABLE asset.assets DROP COLUMN IF EXISTS rating;
ALTER TABLE demo.demos DROP COLUMN IF EXISTS rating;
ALTER TABLE forum.threads DROP COLUMN IF EXISTS rating;
ALTER TABLE forum.messages DROP COLUMN IF EXISTS rating;

ALTER TABLE asset.assets DROP COLUMN IF EXISTS upvotes;
ALTER TABLE asset.assets DROP COLUMN IF EXISTS downvotes;
