ALTER TABLE demo.demos ADD COLUMN views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE asset.assets ADD COLUMN views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE forum.threads ADD COLUMN views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE forum.messages ADD COLUMN views INTEGER NOT NULL DEFAULT 0;

---- create above / drop below ----

ALTER TABLE demo.demos DROP COLUMN IF EXISTS views;
ALTER TABLE asset.assets DROP COLUMN IF EXISTS views;
ALTER TABLE forum.threads DROP COLUMN IF EXISTS views;
ALTER TABLE forum.messages DROP COLUMN IF EXISTS views;
