# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "frontend-dev" ]
  pull_request:
    branches: [ "main", "frontend-dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm run build
    - run: pwd
    - run: ls -al
    - run: ls -al .output
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gamehangar-build
        path: |
          /home/runner/work/godot-fiddle/godot-fiddle/frontend/.output
